{% set name = "pycontrails" %}
{% set version = "0.52.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycontrails-{{ version }}.tar.gz
  sha256: 85248d695f6b320896c9a2ffea5d560411570f0c57cbc85def0ef417377345ee

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - setuptools-scm
    - wheel
    - cython
    - numpy >=2.0.0
    - pip
  run:
    - python
    - boto3 >=1.20
    - cartopy >=0.22
    - cdsapi >=0.4
    - cfgrib >=0.9
    - dask-core >=2022.3
    - eccodes >=1.4
    - ecmwf-api-client >=1.6
    - fsspec >=2022.7
    - gcsfs >=2022.7
    - google-cloud-storage >=2.1
    - h5netcdf >=1.2
    - ipywidgets >=7.6
    - jupyterlab >=2.2
    - lxml >=5.1.0
    - matplotlib-base >=3.3
    - netcdf4 >=1.6
    - numpy <2.0.0
    - opencv >=4.5
    - overrides >=6.1
    - pandas >=2.2
    - platformdirs >=3.0
    - pyproj >=3.5
    - requests >=2.25
    - scikit-image >=0.18
    - scikit-learn >=0.23
    - scipy >=1.10
    - seaborn >=0.11
    - shapely >=2.0
    - tqdm >=4.61
    - xarray >=2022.3
    - zarr >=2.12

test:
  imports:
    - pycontrails
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://py.contrails.org
  summary: Python library for modeling aviation climate impacts
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://py.contrails.org
  dev_url: https://github.com/contrailcirrus/pycontrails

extra:
  recipe-maintainers:
    - zebengberg
    - mlshapiro
    - thabbott
