{% set name = "pycontrails" %}
{% set version = "0.59.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycontrails-{{ version }}.tar.gz
  sha256: fd1fb6aa985503e006a7e34d9b17947c2360d7f70476c5ce338d0f3dbfaaac59

build:
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2.0.0                          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - cython >=3
    - numpy >=2.0.0
    - setuptools >=77
    - setuptools-scm >=8
  run:
    - python
    - cartopy >=0.22
    - cdsapi >=0.4
    - cfgrib >=0.9
    - dask-core >=2022.3
    - eccodes >=2.38
    - ecmwf-api-client >=1.6
    - fsspec >=2022.7
    - gcsfs >=2022.7
    - geojson >=3.1
    - geopandas >=1.1.1
    - google-cloud-storage >=2.1
    - ipywidgets >=7.6
    - jupyterlab >=2.2
    - matplotlib-base >=3.3
    - netcdf4 >=1.6
    - numpy >=1.22
    - opencv >=4.5
    - pandas >=2.0
    - pillow >=10.3
    - platformdirs >=3.0
    - pyproj >=3.5
    - rasterio >=1.3
    - requests >=2.25
    - s3fs >=2022.7
    - scikit-image >=0.18
    - scipy >=1.12
    - shapely >=2.0
    - tqdm >=4.61
    - typing-extensions >=4.5
    - xarray >=2022.3
    - zarr >=2.12

test:
  imports:
    - pycontrails
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://py.contrails.org
  summary: Python library for modeling aviation climate impacts
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://py.contrails.org
  dev_url: https://github.com/contrailcirrus/pycontrails

extra:
  recipe-maintainers:
    - zebengberg
    - mlshapiro
    - thabbott
