{% set name = "pycontrails" %}
{% set version = "0.54.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycontrails-{{ version }}.tar.gz
  sha256: 188c42eb5c48072e4d258087848806dadd41b221566a0c1f0cce4b4071df81ea

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2.0.0                          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - cython >=3
    - numpy >=2.0.0
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python
    - boto3 >=1.20
    - cartopy >=0.22
    - cdsapi >=0.4
    - cfgrib >=0.9
    - dask-core >=2022.3
    - eccodes >=2.38
    - ecmwf-api-client >=1.6
    - fsspec >=2022.7
    - gcsfs >=2022.7
    - google-cloud-storage >=2.1
    - ipywidgets >=7.6
    - jupyterlab >=2.2
    - matplotlib-base >=3.3
    - netcdf4 >=1.6
    - numpy >=1.22
    - opencv >=4.5
    - pandas >=2.2
    - platformdirs >=3.0
    - pyproj >=3.5
    - requests >=2.25
    - scikit-image >=0.18
    - scipy >=1.10
    - shapely >=2.0
    - tqdm >=4.61
    - typing-extensions >=4.5
    - xarray >=2022.3
    - zarr >=2.12

test:
  imports:
    - pycontrails
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://py.contrails.org
  summary: Python library for modeling aviation climate impacts
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://py.contrails.org
  dev_url: https://github.com/contrailcirrus/pycontrails

extra:
  recipe-maintainers:
    - zebengberg
    - mlshapiro
    - thabbott
